version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.example
    environment:
      - MONGODB_URI=mongodb://mongo:27017/college_health
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "5174:4173"
    environment:
      - VITE_API_BASE=http://localhost:5000/api

volumes:
  mongo-data:
